/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_renren_face_FaceInterface */

#ifndef _Included_com_renren_face_FaceInterface
#define _Included_com_renren_face_FaceInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_renren_face_FaceInterface
 * Method:    add
 * Signature: (FF)F
 */
JNIEXPORT jfloat JNICALL Java_com_renren_face_FaceInterface_add
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     com_renren_face_FaceInterface
 * Method:    sum
 * Signature: (FFF)F
 */
JNIEXPORT jfloat JNICALL Java_com_renren_face_FaceInterface_sum
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
