/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_renren_face_FaceInterface */

#ifndef _Included_com_renren_face_FaceInterface
#define _Included_com_renren_face_FaceInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_renren_face_FaceInterface
 * Method:    add
 * Signature: (FF)F
 */
JNIEXPORT jfloat JNICALL Java_com_renren_face_FaceInterface_add
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     com_renren_face_FaceInterface
 * Method:    sum
 * Signature: (FFF)F
 */
JNIEXPORT jfloat JNICALL Java_com_renren_face_FaceInterface_sum
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     com_renren_face_FaceInterface
 * Method:    SetString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_renren_face_FaceInterface_SetString
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_renren_face_FaceInterface
 * Method:    SetByte
 * Signature: (B)B
 */
JNIEXPORT jbyte JNICALL Java_com_renren_face_FaceInterface_SetByte
  (JNIEnv *, jclass, jbyte);

/*
 * Class:     com_renren_face_FaceInterface
 * Method:    SetByteArray
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_renren_face_FaceInterface_SetByteArray
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_renren_face_FaceInterface
 * Method:    SetInt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_renren_face_FaceInterface_SetInt
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_renren_face_FaceInterface
 * Method:    SetIntArray
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_renren_face_FaceInterface_SetIntArray
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     com_renren_face_FaceInterface
 * Method:    SetLong
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_renren_face_FaceInterface_SetLong
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_renren_face_FaceInterface
 * Method:    SetLongArray
 * Signature: ([J)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_renren_face_FaceInterface_SetLongArray
  (JNIEnv *, jclass, jlongArray);

/*
 * Class:     com_renren_face_FaceInterface
 * Method:    SetFloat
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_com_renren_face_FaceInterface_SetFloat
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     com_renren_face_FaceInterface
 * Method:    SetFloatArray
 * Signature: ([F)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_renren_face_FaceInterface_SetFloatArray
  (JNIEnv *, jclass, jfloatArray);

/*
 * Class:     com_renren_face_FaceInterface
 * Method:    SetDouble
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_com_renren_face_FaceInterface_SetDouble
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     com_renren_face_FaceInterface
 * Method:    SetDoubleArray
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_renren_face_FaceInterface_SetDoubleArray
  (JNIEnv *, jclass, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
